# == This file defines the page layouts for new pages.
#
# For further information please see http://guides.alchemy-cms.com/stable/page_layouts.html

- name: index
  unique: true
  elements: [article]
  autogenerate: [article]
- name: simple_page
  unique: false
  layoutpage: true
  elements: [article]
- name: pahe
  unique: false
  elements: [article]
  autogenerate: [article]